create database projects;
use projects;

drop table raw_data;

create table raw_data (
Transaction_ID int,
Date varchar(50),
Customer_ID varchar(20),
Gender varchar(10),
Age int,
Product_Category varchar(100),
Quantity int,
Price_per_Unit decimal(10,2),
Total_Amount decimal(10,2)
);

select year(str_to_date(Date,'%d-%m-%Y')) as Year,
month(str_to_date(Date,'%d-%m-%Y')) as Month,
sum(Total_Amount) as Total_Revenue
from raw_data
group by Year,Month
order by Total_Revenue desc;

select year(str_to_date(Date,'%d-%m-%Y')) as Year,
month(str_to_date(Date,'%d-%m-%Y')) as Month,
sum(Total_Amount)/count(distinct Customer_ID) as Average_Order_Value
from raw_data
group by Year,Month
order by Average_Order_Value desc;

select year(str_to_date(Date,'%d-%m-%Y')) as Year,
month(str_to_date(Date,'%d-%m-%Y')) as Month,Product_Category,
sum(Total_Amount)/count(distinct Customer_ID) as Average_Order_Value
from raw_data
group by Year,Month,Product_Category
order by Average_Order_Value desc;

select year(str_to_date(Date,'%d-%m-%Y')) as Year,
month(str_to_date(Date,'%d-%m-%Y')) as Month,
Count(distinct Customer_ID) as Count_of_Customers
from raw_data
group by Year,Month
order by Count_of_Customers desc;

select * from raw_data;

-- Top  revenue generating Product Category

select Product_Category,sum(Total_Amount) as Total_Revenue 
from raw_data 
group by Product_Category 
order by Total_Revenue desc; 

-- Most Selling Product Category

select Product_Category,sum(Quantity) as Total_Units_Sold
from raw_data
group by Product_Category
order by Total_Units_Sold desc;

-- Insights 1 - 
-- Electronics - Most Revenue / Second most no. of units sold
-- Clothing - Second most Revenue / most units sold
-- Beauty - Least Revenue  / Least units sold

-- Average Price per Unit for each Category

select Product_Category,avg(Price_per_Unit) as Avg_Price_Per_Unit
from raw_data
group by Product_Category
order by Avg_Price_Per_Unit desc;

-- Count of unique customer for each category

select Product_Category,count(distinct Customer_ID) as Count_of_Customers
from raw_data
group by Product_Category
order by Count_of_Customers desc;

-- Revenue Generated per Customer

select Product_Category,sum(Total_Amount)/count(distinct Customer_ID) as Revenue_per_Customer
from raw_data
group by Product_Category
order by Revenue_per_Customer desc;

-- Insights 2
-- Beauty - Highest Revenue per Customer / Highest avg price 
-- Electronics - Second most Revenue per Customer / second most avg price
-- Clothing - Least Revenue per Customer / least avg price

-- count of items bought by gender

select Gender,Product_Category,count(Product_Category) as Count_of_Customers
from raw_data
group by Gender,Product_Category
order by Count_of_Customers asc
limit 5;

-- Insights 3
-- 1. Male + Clothing - 177
-- 2. Female + Clothing - 174
-- 3. Male + Electronics - 172
-- 4. Female + Electronics - 170
-- 5. Female + Beauty -166

-- most revenue generated in each category by gender

select Gender,Product_Category,sum(Total_Amount) as Total_Revenue
from raw_data
group by Gender,Product_Category
order by Total_Revenue desc;

-- Insights 4
-- Top 3 most revenue generated by each product category and gender
-- 1. Female + Clothing - 81k
-- 2. Male + Electronics = 80k
-- 3. Female + Electronics =76.7k

-- Revenue per Customer by Product_Category and Gender
select Gender,Product_Category,sum(Total_Amount)/count(distinct Customer_ID) as Revenue_Per_Customer
from raw_data
group by Gender,Product_Category
order by Revenue_Per_Customer desc;

-- Avg Quantity per Transactions by Product Category and Gender

select Gender,Product_Category,avg(Quantity) as Avg_Quantity
from raw_data
group by Gender,Product_Category
order by Avg_Quantity desc;

select Gender,Product_Category,avg(Price_Per_Unit) as Avg_Price_Per_Unit
from raw_data
group by Product_Category,Gender
order by Avg_Price_Per_Unit desc;

-- Insights 5 
-- Top Revenue per Customer categories
-- 1. Male + Beauty - Highest Revenue per Customer
-- 2. Female + Clothing - Second Highest Revenue per Customer
-- 3. Male + Electronics - Third Highest Revenue per Customer

-- Top avg quantity sold
-- 1. Female +Electronics = 2.58
-- 2. Male + Clothing = 2.55
-- 3. Female + Clothing = 2.53

-- Top Price Per Unit generated by Product Category and Gender
-- 1. Male + Beauty = 186
-- 2. Male + Electronics = 185
-- 3. Female + Beauty = 182

select Gender,Product_Category,count(distinct Transaction_ID) as Number_of_Transactions
from raw_data
group by Gender,Product_Category
order by Number_of_Transactions desc;

-- Highest Spending Customers

select Customer_ID from (select Customer_ID,sum(Total_Amount) as Total_Spend
from raw_data
group by Customer_ID
order by Total_Spend desc) as count_revenue
where Total_Spend = 2000.00;

select distinct Customer_ID,Product_Category,sum(Total_Amount) as Total_Spend
from raw_data
group by Customer_ID,Product_Category
order by Total_Spend desc;

